user:
  valid_email_regex: !ruby/regexp /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  email:
    min_length: 5
    max_length: 50
  name:
    max_length: 50
  password:
    min_length: 6
  phone_number:
    length: 10
model:
  limitation: 6
  limited: 10
genre:
  name:
    max_length: 50
movie:
  name:
    max_length: 50
  content:
    max_length: 1000
payment:
  expired: 15
